/*
 * MainPanel.java
 *
 * Created on __DATE__, __TIME__
 */

package bsp.ui;

import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 * 
 * @author __USER__
 */
public class MainPanel extends javax.swing.JPanel {

	/** Creates new form MainPanel */
	public MainPanel() {
		initComponents();
		initFChooser();
		//System.out.println(p_Body.getPreferredSize());
		javax.swing.JButton test = new javax.swing.JButton("Test");
		test.setBounds(0, 45, 315, 330);
		this.add(test);
		this.repaint();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		fileChooser = new javax.swing.JFileChooser();
		ll_Path = new javax.swing.JLabel();
		TF_Path = new javax.swing.JTextField();
		b_Open = new javax.swing.JButton();
		jSeparator1 = new javax.swing.JSeparator();
		b_Load = new javax.swing.JButton();
		b_TimeFrame = new javax.swing.JButton();
		b_Send = new javax.swing.JButton();
		jSeparator2 = new javax.swing.JSeparator();

		setPreferredSize(new java.awt.Dimension(315, 430));
		setRequestFocusEnabled(false);

		ll_Path.setFont(new java.awt.Font("Segoe UI", 0, 14));
		ll_Path.setText("File: ");

		TF_Path.setEditable(false);
		TF_Path.setText("Aaron Cai");

		b_Open.setText("Open..");
		b_Open.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				b_OpenActionPerformed(evt);
			}
		});

		b_Load.setText("Load");
		b_Load.setPreferredSize(new java.awt.Dimension(95, 25));

		b_TimeFrame.setText("Time Frame");

		b_Send.setText("Send");
		b_Send.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				b_SendActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(ll_Path)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(TF_Path,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										185, Short.MAX_VALUE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(b_Open).addContainerGap())
				.addComponent(jSeparator1,
						javax.swing.GroupLayout.DEFAULT_SIZE, 315,
						Short.MAX_VALUE)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(b_Load,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										103,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(b_Send,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										77,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(b_TimeFrame)
								.addContainerGap(14, Short.MAX_VALUE))
				.addComponent(jSeparator2,
						javax.swing.GroupLayout.DEFAULT_SIZE, 315,
						Short.MAX_VALUE));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(ll_Path)
												.addComponent(b_Open)
												.addComponent(
														TF_Path,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jSeparator1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										10,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										320, Short.MAX_VALUE)
								.addComponent(jSeparator2,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										10,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														b_Load,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(b_TimeFrame)
												.addComponent(b_Send))
								.addContainerGap()));
	}// </editor-fold>
	//GEN-END:initComponents

	private void b_SendActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		javax.swing.JFrame parent = (javax.swing.JFrame) this.getRootPane()
				.getParent();
		parent.remove(this);
		parent.repaint();
	}

	private void b_OpenActionPerformed(java.awt.event.ActionEvent evt) {
		int reval = fileChooser.showOpenDialog(this);
		if (reval == JFileChooser.APPROVE_OPTION) {
			TF_Path.setText(fileChooser.getSelectedFile().getPath());
			TF_Path.setToolTipText(TF_Path.getText());
			//System.out.println(TF_Path.getText());
		}
	}

	// Initialise the file chooser. Only the .ppt or .pdf files
	// can be shown
	private void initFChooser() {
		FileNameExtensionFilter filter = new FileNameExtensionFilter(
				"ppt or pdf", "ppt", "pdf");
		fileChooser.setAcceptAllFileFilterUsed(false);
		fileChooser.setFileFilter(filter);
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JTextField TF_Path;
	private javax.swing.JButton b_Load;
	private javax.swing.JButton b_Open;
	private javax.swing.JButton b_Send;
	private javax.swing.JButton b_TimeFrame;
	private javax.swing.JFileChooser fileChooser;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JSeparator jSeparator2;
	private javax.swing.JLabel ll_Path;
	// End of variables declaration//GEN-END:variables

}